import {CategoryFormConfig} from './product-form.types';

export const extensionCordsConfig: CategoryFormConfig = {
  id: 'extension_cords',
  name: 'Extension Cords & Surge Protectors',
  fields: [
    {
      name: 'length',
      type: 'number',
      label: 'Cord Length',
      required: true,
      unit: 'm',
      group: 'specifications',
    },
    {
      name: 'surgeProtection',
      type: 'radio',
      label: 'Surge Protection',
      required: true,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'socketCount',
      type: 'number',
      label: 'Number of Sockets',
      required: true,
      group: 'specifications',
    },
    {
      name: 'powerRating',
      type: 'number',
      label: 'Maximum Power Rating',
      required: true,
      unit: 'W',
      group: 'specifications',
    },
    {
      name: 'jouleRating',
      type: 'number',
      label: 'Joule Rating (for surge protectors)',
      required: false,
      unit: 'J',
      group: 'specifications',
    },
    {
      name: 'usbPorts',
      type: 'number',
      label: 'USB Charging Ports',
      required: false,
      group: 'features',
    },
    {
      name: 'usbPowerOutput',
      type: 'select',
      label: 'USB Port Total Power',
      required: false,
      options: ['None', '1A Total', '2.1A Total', '3.4A Total', '4.8A Total'],
      group: 'features',
    },
    {
      name: 'socketType',
      type: 'select',
      label: 'Socket Type/Standard',
      required: true,
      options: ['Type A (US/Japan)', 'Type B (US/Japan)', 'Type C (Euro)', 'Type G (UK)', 'Type I (AU/NZ)', 'Universal'],
      group: 'specifications',
    },
    {
      name: 'circuitBreaker',
      type: 'radio',
      label: 'Circuit Breaker/Reset Button',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'usageRating',
      type: 'select',
      label: 'Usage Rating',
      required: true,
      options: ['Indoor Only', 'Indoor/Outdoor', 'Weather Resistant'],
      group: 'specifications',
    },
    {
      name: 'color',
      type: 'select',
      label: 'Color',
      required: false,
      options: ['White', 'Black', 'Gray', 'Beige'],
      group: 'physical',
    },
    {
      name: 'warranty',
      type: 'select',
      label: 'Warranty',
      required: false,
      options: ['1 Year', '2 Years', '5 Years', 'Lifetime'],
      group: 'additional',
    }
  ],
};
