import {CategoryFormConfig} from './product-form.types';

export const hardDiskEnclosuresConfig: CategoryFormConfig = {
  id: 'hard_disk_enclosures',
  name: 'Hard Disk Enclosures',
  fields: [
    {
      name: 'compatibleDriveTypes',
      type: 'select',
      label: 'Compatible Drive Types',
      required: true,
      options: ['3.5" HDD', '2.5" HDD', 'Both 3.5" & 2.5" HDD', 'Multiple Sizes'],
      group: 'specifications',
    },
    {
      name: 'driveCapacity',
      type: 'select',
      label: 'Maximum Drive Capacity',
      required: false,
      options: ['Up to 2TB', 'Up to 4TB', 'Up to 8TB', 'Up to 16TB', 'Up to 20TB+', 'No Practical Limit'],
      group: 'specifications',
    },
    {
      name: 'driveBays',
      type: 'number',
      label: 'Number of Drive Bays',
      required: true,
      group: 'specifications',
    },
    {
      name: 'interfaceType',
      type: 'checkbox-group',
      label: 'Interface Type',
      required: true,
      options: ['USB 2.0', 'USB 3.0', 'USB 3.1', 'USB 3.2', 'USB-C', 'Thunderbolt 3', 'Thunderbolt 4', 'eSATA', 'Multiple'],
      group: 'specifications',
    },
    {
      name: 'dataTransferRate',
      type: 'select',
      label: 'Maximum Data Transfer Rate',
      required: false,
      options: ['Up to 480 Mbps', 'Up to 5 Gbps', 'Up to 10 Gbps', 'Up to 20 Gbps', 'Up to 40 Gbps'],
      group: 'specifications',
    },
    {
      name: 'raidSupport',
      type: 'radio',
      label: 'RAID Support',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'raidModes',
      type: 'checkbox-group',
      label: 'Supported RAID Modes',
      required: false,
      options: ['Not Applicable', 'RAID 0', 'RAID 1', 'RAID 5', 'RAID 10', 'JBOD', 'Multiple Modes'],
      group: 'specifications',
    },
    {
      name: 'toollessInstallation',
      type: 'radio',
      label: 'Toolless Installation',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'coolingSystem',
      type: 'select',
      label: 'Cooling System',
      required: false,
      options: ['None', 'Passive Cooling', 'Single Fan', 'Multiple Fans', 'Advanced Cooling'],
      group: 'features',
    },
    {
      name: 'powerSupply',
      type: 'select',
      label: 'Power Supply',
      required: false,
      options: ['Bus-Powered', 'External Adapter', 'Internal Power Supply', 'Multiple Options'],
      group: 'specifications',
    },
    {
      name: 'hotSwappable',
      type: 'radio',
      label: 'Hot-Swappable',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'material',
      type: 'select',
      label: 'Primary Material',
      required: false,
      options: ['Plastic', 'Aluminum', 'Steel', 'Mixed Materials'],
      group: 'physical',
    },
    {
      name: 'ledIndicator',
      type: 'radio',
      label: 'LED Status Indicator',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'compatibleSystems',
      type: 'checkbox-group',
      label: 'Compatible Operating Systems',
      required: false,
      options: ['Windows', 'macOS', 'Linux', 'Android', 'Multiple'],
      group: 'compatibility',
    },
    {
      name: 'cableIncluded',
      type: 'radio',
      label: 'Connection Cable Included',
      required: false,
      options: ['Yes', 'No'],
      group: 'package',
    },
    {
      name: 'color',
      type: 'select',
      label: 'Color',
      required: false,
      options: ['Black', 'Silver', 'White', 'Blue', 'Other'],
      group: 'physical',
    },
    {
      name: 'warranty',
      type: 'select',
      label: 'Warranty',
      required: false,
      options: ['1 Year', '2 Years', '3 Years', '5 Years', 'Lifetime'],
      group: 'additional',
    }
  ],
};
