import {CategoryFormConfig} from './product-form.types';

export const hdmiToVgaAdaptersConfig: CategoryFormConfig = {
  id: 'hdmi_to_vga_adapters',
  name: 'HDMI to VGA Adapters',
  fields: [
    {
      name: 'maxResolution',
      type: 'select',
      label: 'Maximum Resolution',
      required: true,
      options: ['640×480', '800×600', '1024×768', '1280×1024', '1600×1200', '1920×1080 (1080p)'],
      group: 'specifications',
    },
    {
      name: 'refreshRate',
      type: 'select',
      label: 'Maximum Refresh Rate',
      required: false,
      options: ['60Hz', '75Hz', '85Hz', '120Hz'],
      group: 'specifications',
    },
    {
      name: 'signalConversion',
      type: 'select',
      label: 'Signal Conversion Type',
      required: false,
      options: ['Active', 'Passive'],
      group: 'specifications',
    },
    {
      name: 'audioSupport',
      type: 'radio',
      label: 'Audio Support',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'audioOutput',
      type: 'select',
      label: 'Audio Output (if applicable)',
      required: false,
      options: ['Not Applicable', '3.5mm Jack', 'Built-in Speaker', 'Both'],
      group: 'features',
    },
    {
      name: 'powerRequired',
      type: 'radio',
      label: 'External Power Required',
      required: false,
      options: ['Yes', 'No'],
      group: 'specifications',
    },
    {
      name: 'powerSource',
      type: 'select',
      label: 'Power Source (if applicable)',
      required: false,
      options: ['Not Applicable', 'USB', 'Wall Adapter', 'HDMI Port'],
      group: 'specifications',
    },
    {
      name: 'compatibleDevices',
      type: 'select',
      label: 'Primary Compatible Source Devices',
      required: false,
      options: ['PC/Laptop', 'Gaming Consoles', 'Media Players', 'All HDMI Sources'],
      group: 'compatibility',
    },
    {
      name: 'chipset',
      type: 'select',
      label: 'Chipset',
      required: false,
      options: ['Realtek', 'Chrontel', 'Genesis', 'Other', 'Not Specified'],
      group: 'specifications',
    },
    {
      name: 'cableLength',
      type: 'number',
      label: 'Cable Length (if applicable)',
      required: false,
      unit: 'cm',
      group: 'physical',
    },
    {
      name: 'connectorType',
      type: 'select',
      label: 'VGA Connector Type',
      required: false,
      options: ['Standard DB-15', 'Mini VGA', 'Other'],
      group: 'specifications',
    },
    {
      name: 'color',
      type: 'select',
      label: 'Color',
      required: false,
      options: ['Black', 'White', 'Silver', 'Blue'],
      group: 'physical',
    },
    {
      name: 'warranty',
      type: 'select',
      label: 'Warranty',
      required: false,
      options: ['1 Year', '2 Years', '3 Years', '5 Years', 'Lifetime'],
      group: 'additional',
    }
  ],
};
