import {CategoryFormConfig} from './product-form.types';

export const laptopPowerCablesConfig: CategoryFormConfig = {
  id: 'laptop_power_cables',
  name: 'Laptop Power Cables',
  fields: [
    {
      name: 'connectorType',
      type: 'select',
      label: 'Connector Type',
      required: true,
      options: ['Barrel Plug', 'USB-C PD', 'MagSafe', 'Surface Connect', 'Lenovo Rectangular', 'Dell Oval'],
      group: 'specifications',
    },
    {
      name: 'length',
      type: 'number',
      label: 'Cable Length',
      required: true,
      unit: 'm',
      group: 'specifications',
    },
    {
      name: 'wattageRating',
      type: 'select',
      label: 'Wattage Rating',
      required: true,
      options: ['45W', '60W', '65W', '85W', '90W', '100W', '120W', '170W', '200W+'],
      group: 'specifications',
    },
    {
      name: 'voltageOutput',
      type: 'select',
      label: 'Voltage Output',
      required: true,
      options: ['5V', '9V', '12V', '15V', '19V', '20V', 'Variable (PD)'],
      group: 'specifications',
    },
    {
      name: 'compatibleBrands',
      type: 'select',
      label: 'Compatible Brands',
      required: false,
      options: ['Apple', 'Dell', 'HP', 'Lenovo', 'ASUS', 'Acer', 'Microsoft', 'Samsung', 'Universal'],
      group: 'compatibility',
    },
    {
      name: 'compatibleModels',
      type: 'textarea',
      label: 'Compatible Models',
      required: false,
      placeholder: 'List compatible laptop models',
      group: 'compatibility',
    },
    {
      name: 'barrelDimensions',
      type: 'select',
      label: 'Barrel Dimensions (if applicable)',
      required: false,
      options: ['5.5mm x 2.1mm', '5.5mm x 2.5mm', '4.5mm x 3.0mm', '4.0mm x 1.7mm', '7.4mm x 5.0mm', 'Other'],
      group: 'specifications',
    },
    {
      name: 'originalPart',
      type: 'radio',
      label: 'Original/OEM Part',
      required: false,
      options: ['Yes', 'No'],
      group: 'additional',
    },
    {
      name: 'adapterIncluded',
      type: 'radio',
      label: 'Power Adapter Included',
      required: true,
      options: ['Yes', 'No'],
      group: 'package',
    },
    {
      name: 'color',
      type: 'select',
      label: 'Color',
      required: false,
      options: ['Black', 'White', 'Silver'],
      group: 'physical',
    },
    {
      name: 'warranty',
      type: 'select',
      label: 'Warranty',
      required: false,
      options: ['1 Year', '2 Years', '5 Years', 'Lifetime'],
      group: 'additional',
    }
  ],
};
