import {CategoryFormConfig} from './product-form.types';

export const lightningTo35mmConfig: CategoryFormConfig = {
  id: 'lightning_to_35mm',
  name: 'Lightning to 3.5mm Adapter',
  fields: [
    {
      name: 'length',
      type: 'number',
      label: 'Cable Length',
      required: true,
      unit: 'cm',
      group: 'specifications',
    },
    {
      name: 'audioQuality',
      type: 'select',
      label: 'Audio Quality',
      required: false,
      options: ['Standard', 'HD Audio', 'Premium'],
      group: 'specifications',
    },
    {
      name: 'dacType',
      type: 'select',
      label: 'DAC Type',
      required: false,
      options: ['Standard', 'Premium', 'Hi-Fi', 'Not Specified'],
      group: 'specifications',
    },
    {
      name: 'impedanceSupport',
      type: 'select',
      label: 'Headphone Impedance Support',
      required: false,
      options: ['Standard (Up to 32Ω)', 'Medium (Up to 100Ω)', 'High (100Ω+)'],
      group: 'specifications',
    },
    {
      name: 'remoteControl',
      type: 'radio',
      label: 'Remote Control Support',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'micSupport',
      type: 'radio',
      label: 'Microphone Support',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'mfiCertified',
      type: 'radio',
      label: 'MFi Certified',
      required: true,
      options: ['Yes', 'No'],
      group: 'certification',
    },
    {
      name: 'originalApple',
      type: 'radio',
      label: 'Original Apple Product',
      required: false,
      options: ['Yes', 'No'],
      group: 'additional',
    },
    {
      name: 'compatibleDevices',
      type: 'select',
      label: 'Compatible Apple Devices',
      required: false,
      options: ['iPhone 7 and newer', 'iPad Pro', 'All Lightning Port Devices', 'Specific Models Only'],
      group: 'compatibility',
    },
    {
      name: 'chargingSupport',
      type: 'radio',
      label: 'Simultaneous Charging Support',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'color',
      type: 'select',
      label: 'Color',
      required: false,
      options: ['White', 'Black', 'Silver'],
      group: 'physical',
    },
    {
      name: 'warranty',
      type: 'select',
      label: 'Warranty',
      required: false,
      options: ['1 Year', '2 Years', '3 Years', '5 Years', 'Lifetime'],
      group: 'additional',
    }
  ],
};
