import {CategoryFormConfig} from './product-form.types';

export const lightningToUsbAConfig: CategoryFormConfig = {
  id: 'lightning_to_usb_a',
  name: 'Lightning to USB-A',
  fields: [
    {
      name: 'length',
      type: 'number',
      label: 'Cable Length',
      required: true,
      unit: 'm',
      group: 'specifications',
    },
    {
      name: 'dataTransferRate',
      type: 'select',
      label: 'Data Transfer Rate',
      required: false,
      options: ['Up to 480 Mbps', 'Up to 5 Gbps'],
      group: 'specifications',
    },
    {
      name: 'chargingSpeed',
      type: 'select',
      label: 'Charging Speed',
      required: false,
      options: ['Standard', '12W', '18W'],
      group: 'specifications',
    },
    {
      name: 'connectorStyle',
      type: 'select',
      label: 'Connector Style',
      required: false,
      options: ['Straight', 'Right Angle', 'L-Shaped'],
      group: 'physical',
    },
    {
      name: 'mfiCertified',
      type: 'radio',
      label: 'MFi Certified',
      required: true,
      options: ['Yes', 'No'],
      group: 'certification',
    },
    {
      name: 'originalApple',
      type: 'radio',
      label: 'Original Apple Product',
      required: false,
      options: ['Yes', 'No'],
      group: 'additional',
    },
    {
      name: 'cableMaterial',
      type: 'select',
      label: 'Cable Material',
      required: false,
      options: ['Standard PVC', 'Braided Nylon', 'TPE', 'Premium Materials'],
      group: 'physical',
    },
    {
      name: 'connectorFinish',
      type: 'select',
      label: 'Connector Finish',
      required: false,
      options: ['Standard', 'Gold-Plated', 'Aluminum'],
      group: 'physical',
    },
    {
      name: 'compatibleDevices',
      type: 'select',
      label: 'Compatible Apple Devices',
      required: false,
      options: ['iPhone', 'iPad', 'iPod', 'AirPods', 'All Lightning Port Devices'],
      group: 'compatibility',
    },
    {
      name: 'reinforcedConnector',
      type: 'radio',
      label: 'Reinforced Connector',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'color',
      type: 'select',
      label: 'Color',
      required: false,
      options: ['White', 'Black', 'Silver', 'Gold', 'Red', 'Blue'],
      group: 'physical',
    },
    {
      name: 'warranty',
      type: 'select',
      label: 'Warranty',
      required: false,
      options: ['1 Year', '2 Years', '3 Years', '5 Years', 'Lifetime'],
      group: 'additional',
    }
  ],
};
