import {CategoryFormConfig} from './product-form.types';

export const magsafeCablesConfig: CategoryFormConfig = {
  id: 'magsafe_charging_cables',
  name: 'MagSafe Charging Cables',
  fields: [
    {
      name: 'length',
      type: 'number',
      label: 'Cable Length',
      required: true,
      unit: 'm',
      group: 'specifications',
    },
    {
      name: 'maxWattage',
      type: 'select',
      label: 'Maximum Wattage',
      required: true,
      options: ['15W', '20W', '30W'],
      group: 'specifications',
    },
    {
      name: 'magsafeGeneration',
      type: 'select',
      label: 'MagSafe Generation',
      required: true,
      options: ['MagSafe 1', 'MagSafe 2', 'MagSafe 3', 'MagSafe Wireless (iPhone)'],
      group: 'specifications',
    },
    {
      name: 'compatibleDevices',
      type: 'select',
      label: 'Compatible With',
      required: true,
      options: ['MacBook', 'MacBook Pro', 'MacBook Air', 'iPhone 12/13/14/15 Series', 'Multiple Devices'],
      group: 'compatibility',
    },
    {
      name: 'compatibleModels',
      type: 'textarea',
      label: 'Compatible Models',
      required: false,
      placeholder: 'List specific compatible device models',
      group: 'compatibility',
    },
    {
      name: 'sourceConnector',
      type: 'select',
      label: 'Source-End Connector',
      required: true,
      options: ['USB-C', 'USB-A', 'Lightning', 'Direct to Adapter'],
      group: 'specifications',
    },
    {
      name: 'originalApple',
      type: 'radio',
      label: 'Apple Original/Certified',
      required: false,
      options: ['Yes', 'No'],
      group: 'certification',
    },
    {
      name: 'mfiCertified',
      type: 'radio',
      label: 'MFi Certified',
      required: false,
      options: ['Yes', 'No'],
      group: 'certification',
    },
    {
      name: 'passThroughCharging',
      type: 'radio',
      label: 'Pass-Through Charging Support',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'color',
      type: 'select',
      label: 'Color',
      required: false,
      options: ['White', 'Black', 'Silver', 'Space Gray'],
      group: 'physical',
    },
    {
      name: 'warranty',
      type: 'select',
      label: 'Warranty',
      required: false,
      options: ['1 Year', '2 Years', '5 Years', 'Lifetime'],
      group: 'additional',
    }
  ],
};
