import {CategoryFormConfig} from './product-form.types';

export const memoryCardReadersConfig: CategoryFormConfig = {
  id: 'memory_card_readers',
  name: 'Memory Card Readers',
  fields: [
    {
      name: 'readerType',
      type: 'select',
      label: 'Reader Type',
      required: true,
      options: ['Single-format', 'Multi-format', 'All-in-One'],
      group: 'specifications',
    },
    {
      name: 'connectionInterface',
      type: 'select',
      label: 'Connection Interface',
      required: true,
      options: ['USB-A', 'USB-C', 'Micro USB', 'Thunderbolt', 'Lightning', 'Internal'],
      group: 'specifications',
    },
    {
      name: 'usbVersion',
      type: 'select',
      label: 'USB Version',
      required: true,
      options: ['USB 1.0/1.1', 'USB 2.0', 'USB 3.0', 'USB 3.1', 'USB 3.2'],
      group: 'specifications',
    },
    {
      name: 'supportedCardFormats',
      type: 'select',
      label: 'Supported Card Formats',
      required: true,
      options: ['SD', 'SDHC', 'SDXC', 'microSD', 'microSDHC', 'microSDXC', 'CompactFlash (CF)', 'CFexpress', 'XQD', 'Memory Stick', 'Memory Stick Pro', 'Memory Stick Duo', 'MMC', 'xD-Picture Card', 'UFS', 'CFast', 'M.2'],
      group: 'specifications',
    },
    {
      name: 'transferSpeed',
      type: 'select',
      label: 'Maximum Transfer Speed',
      required: false,
      options: ['Up to 480 Mbps', 'Up to 5 Gbps', 'Up to 10 Gbps', 'Up to 20 Gbps'],
      group: 'specifications',
    },
    {
      name: 'simultaneousReadWrite',
      type: 'radio',
      label: 'Simultaneous Read/Write',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'compactDesign',
      type: 'radio',
      label: 'Compact Design',
      required: false,
      options: ['Yes', 'No'],
      group: 'physical',
    },
    {
      name: 'ledIndicator',
      type: 'radio',
      label: 'Activity LED Indicator',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'color',
      type: 'select',
      label: 'Color',
      required: false,
      options: ['Black', 'White', 'Silver', 'Gray', 'Blue'],
      group: 'physical',
    },
    {
      name: 'warranty',
      type: 'select',
      label: 'Warranty',
      required: false,
      options: ['1 Year', '2 Years', '3 Years', '5 Years', 'Lifetime'],
      group: 'additional',
    }
  ],
};
