import {CategoryFormConfig} from './product-form.types';

export const microUsbToUsbAConfig: CategoryFormConfig = {
  id: 'micro_usb_to_usb_a',
  name: 'Micro-USB to USB-A',
  fields: [
    {
      name: 'length',
      type: 'number',
      label: 'Cable Length',
      required: true,
      unit: 'm',
      group: 'specifications',
    },
    {
      name: 'usbVersion',
      type: 'select',
      label: 'USB Version',
      required: true,
      options: ['USB 1.0/1.1', 'USB 2.0', 'USB 3.0', 'USB 3.1'],
      group: 'specifications',
    },
    {
      name: 'dataTransferRate',
      type: 'select',
      label: 'Data Transfer Rate',
      required: false,
      options: ['Up to 12 Mbps', 'Up to 480 Mbps', 'Up to 5 Gbps', 'Up to 10 Gbps'],
      group: 'specifications',
    },
    {
      name: 'fastCharging',
      type: 'radio',
      label: 'Fast Charging Support',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'chargingProtocol',
      type: 'select',
      label: 'Charging Protocol',
      required: false,
      options: ['Standard', 'Quick Charge 2.0', 'Quick Charge 3.0', 'Quick Charge 4.0', 'Samsung Adaptive Fast Charging'],
      group: 'features',
    },
    {
      name: 'maxCurrent',
      type: 'select',
      label: 'Maximum Current',
      required: false,
      options: ['0.5A', '1A', '2A', '2.4A', '3A'],
      group: 'specifications',
    },
    {
      name: 'connectorStyle',
      type: 'select',
      label: 'Connector Style',
      required: false,
      options: ['Straight', 'Right Angle', 'L-Shaped', 'Reversible Micro-USB'],
      group: 'physical',
    },
    {
      name: 'cableMaterial',
      type: 'select',
      label: 'Cable Material',
      required: false,
      options: ['Standard PVC', 'Braided Nylon', 'TPE', 'Premium Materials'],
      group: 'physical',
    },
    {
      name: 'shielding',
      type: 'select',
      label: 'Shielding',
      required: false,
      options: ['Standard', 'Double Shielded', 'Premium Shielding'],
      group: 'specifications',
    },
    {
      name: 'deviceSupport',
      type: 'select',
      label: 'Compatible Devices',
      required: false,
      options: ['Android Phones/Tablets', 'Cameras', 'Bluetooth Speakers', 'GPS Devices', 'All Micro-USB Devices'],
      group: 'compatibility',
    },
    {
      name: 'color',
      type: 'select',
      label: 'Color',
      required: false,
      options: ['Black', 'White', 'Red', 'Blue', 'Green', 'Gold'],
      group: 'physical',
    },
    {
      name: 'warranty',
      type: 'select',
      label: 'Warranty',
      required: false,
      options: ['1 Year', '2 Years', '3 Years', '5 Years', 'Lifetime'],
      group: 'additional',
    }
  ],
};
