import {CategoryFormConfig} from './product-form.types';

export const otgCablesConfig: CategoryFormConfig = {
  id: 'otg_on_the_go_cables',
  name: 'OTG (On-The-Go) Cables',
  fields: [
    {
      name: 'connectorType',
      type: 'select',
      label: 'Connector Configuration',
      required: true,
      options: [
        'Micro-USB to USB-A Female',
        'USB-C to USB-A Female',
        'Lightning to USB-A Female',
        'Micro-USB to USB-C Female',
        'USB-C to USB-C Female'
      ],
      group: 'specifications',
    },
    {
      name: 'usbVersion',
      type: 'select',
      label: 'USB Version',
      required: true,
      options: ['USB 1.0/1.1', 'USB 2.0', 'USB 3.0', 'USB 3.1', 'USB 3.2'],
      group: 'specifications',
    },
    {
      name: 'dataTransferRate',
      type: 'select',
      label: 'Data Transfer Rate',
      required: false,
      options: ['Up to 12 Mbps', 'Up to 480 Mbps', 'Up to 5 Gbps', 'Up to 10 Gbps', 'Up to 20 Gbps'],
      group: 'specifications',
    },
    {
      name: 'powerDelivery',
      type: 'radio',
      label: 'Power Delivery Support',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'length',
      type: 'number',
      label: 'Cable Length',
      required: true,
      unit: 'cm',
      group: 'specifications',
    },
    {
      name: 'cableMaterial',
      type: 'select',
      label: 'Cable Material',
      required: false,
      options: ['Standard PVC', 'Braided Nylon', 'TPE', 'Premium Materials'],
      group: 'physical',
    },
    {
      name: 'deviceSupport',
      type: 'select',
      label: 'Compatible Devices',
      required: false,
      options: ['Android Phones/Tablets', 'iPads/iPhones', 'All OTG-Compatible Devices'],
      group: 'compatibility',
    },
    {
      name: 'peripheralSupport',
      type: 'select',
      label: 'Compatible Peripherals',
      required: false,
      options: [
        'USB Flash Drives',
        'Keyboards/Mice',
        'MIDI Controllers',
        'Card Readers',
        'Game Controllers',
        'All USB Peripherals'
      ],
      group: 'compatibility',
    },
    {
      name: 'powerRequired',
      type: 'radio',
      label: 'External Power Required',
      required: false,
      options: ['Yes', 'No'],
      group: 'specifications',
    },
    {
      name: 'hubFeature',
      type: 'radio',
      label: 'Multiple Port Hub Feature',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'chargingSupport',
      type: 'radio',
      label: 'Simultaneous Charging Support',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'color',
      type: 'select',
      label: 'Color',
      required: false,
      options: ['Black', 'White', 'Silver', 'Red', 'Blue'],
      group: 'physical',
    },
    {
      name: 'warranty',
      type: 'select',
      label: 'Warranty',
      required: false,
      options: ['1 Year', '2 Years', '3 Years', '5 Years', 'Lifetime'],
      group: 'additional',
    }
  ],
};
