import {CategoryFormConfig} from './product-form.types';

export const ssdEnclosuresConfig: CategoryFormConfig = {
  id: 'ssd_enclosures',
  name: 'SSD Enclosures',
  fields: [
    {
      name: 'compatibleDriveTypes',
      type: 'checkbox-group',
      label: 'Compatible Drive Types',
      required: true,
      options: ['2.5" SATA SSD', 'M.2 SATA', 'M.2 NVMe', 'mSATA', 'Multiple Types'],
      group: 'specifications',
    },
    {
      name: 'formFactorsSupported',
      type: 'checkbox-group',
      label: 'M.2 Form Factors Supported',
      required: false,
      options: ['Not Applicable', '2242', '2260', '2280', '22110', 'Multiple Sizes'],
      group: 'specifications',
    },
    {
      name: 'interfaceType',
      type: 'checkbox-group',
      label: 'Interface Type',
      required: true,
      options: ['USB 3.0', 'USB 3.1', 'USB 3.2 Gen 1', 'USB 3.2 Gen 2', 'USB-C', 'Thunderbolt 3', 'Thunderbolt 4', 'Multiple'],
      group: 'specifications',
    },
    {
      name: 'dataTransferRate',
      type: 'select',
      label: 'Maximum Data Transfer Rate',
      required: false,
      options: ['Up to 5 Gbps', 'Up to 10 Gbps', 'Up to 20 Gbps', 'Up to 40 Gbps'],
      group: 'specifications',
    },
    {
      name: 'trimSupport',
      type: 'radio',
      label: 'TRIM Support',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'toollessInstallation',
      type: 'radio',
      label: 'Toolless Installation',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'enclosureMaterial',
      type: 'select',
      label: 'Enclosure Material',
      required: false,
      options: ['Plastic', 'Aluminum', 'Aluminum Alloy', 'Mixed Materials'],
      group: 'physical',
    },
    {
      name: 'thermalSolution',
      type: 'select',
      label: 'Thermal Solution',
      required: false,
      options: ['None', 'Thermal Pad', 'Heat Sink', 'Active Cooling'],
      group: 'features',
    },
    {
      name: 'cableIncluded',
      type: 'radio',
      label: 'Cable Included',
      required: false,
      options: ['Yes', 'No'],
      group: 'package',
    },
    {
      name: 'cableType',
      type: 'select',
      label: 'Included Cable Type',
      required: false,
      options: ['Not Included', 'USB-A to USB-C', 'USB-C to USB-C', 'Thunderbolt', 'Multiple Cables'],
      group: 'package',
    },
    {
      name: 'portableDesign',
      type: 'radio',
      label: 'Portable Design',
      required: false,
      options: ['Yes', 'No'],
      group: 'physical',
    },
    {
      name: 'shockResistant',
      type: 'radio',
      label: 'Shock Resistant',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'ledIndicator',
      type: 'radio',
      label: 'LED Indicator',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'busOrAdapterPowered',
      type: 'select',
      label: 'Power Source',
      required: false,
      options: ['Bus-Powered', 'Adapter-Powered', 'Both Options'],
      group: 'specifications',
    },
    {
      name: 'compatibleSystems',
      type: 'checkbox-group',
      label: 'Compatible Operating Systems',
      required: false,
      options: ['Windows', 'macOS', 'Linux', 'Chrome OS', 'All Major OS'],
      group: 'compatibility',
    },
    {
      name: 'color',
      type: 'select',
      label: 'Color',
      required: false,
      options: ['Black', 'Silver', 'Gray', 'Clear', 'Blue', 'Other'],
      group: 'physical',
    },
    {
      name: 'warranty',
      type: 'select',
      label: 'Warranty',
      required: false,
      options: ['1 Year', '2 Years', '3 Years', '5 Years', 'Lifetime'],
      group: 'additional',
    }
  ],
};
