import {CategoryFormConfig} from './product-form.types';

export const surfaceDockingStationsConfig: CategoryFormConfig = {
  id: 'surface_docking_stations',
  name: 'Surface Docking Stations',
  fields: [
    {
      name: 'compatibleSurfaceModels',
      type: 'checkbox-group',
      label: 'Compatible Surface Models',
      required: true,
      options: [
        'Surface Pro (All)',
        'Surface Pro X',
        'Surface Pro 3/4/5/6/7/8/9',
        'Surface Laptop (All)',
        'Surface Laptop 1/2/3/4/5/6',
        'Surface Book (All)',
        'Surface Book 1/2/3',
        'Surface Go (All)',
        'Surface Go 1/2/3/4',
        'Surface Studio (All)',
        'Multiple Surface Types'
      ],
      group: 'compatibility',
    },
    {
      name: 'connectionType',
      type: 'select',
      label: 'Connection Type',
      required: true,
      options: ['Surface Connect', 'USB-C', 'Surface Connect + USB-C'],
      group: 'specifications',
    },
    {
      name: 'totalPorts',
      type: 'number',
      label: 'Total Number of Ports',
      required: true,
      group: 'specifications',
    },
    {
      name: 'usbCPorts',
      type: 'number',
      label: 'USB-C Ports',
      required: false,
      group: 'specifications',
    },
    {
      name: 'usbAPorts',
      type: 'number',
      label: 'USB-A Ports',
      required: false,
      group: 'specifications',
    },
    {
      name: 'displayPorts',
      type: 'checkbox-group',
      label: 'Display Port Types',
      required: false,
      options: ['HDMI', 'DisplayPort', 'Mini DisplayPort', 'VGA', 'Multiple Types'],
      group: 'specifications',
    },
    {
      name: 'maxDisplays',
      type: 'select',
      label: 'Maximum External Displays',
      required: false,
      options: ['1', '2', '3', '4+'],
      group: 'specifications',
    },
    {
      name: 'ethernetPort',
      type: 'radio',
      label: 'Ethernet Port',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'audioJacks',
      type: 'select',
      label: 'Audio Jacks',
      required: false,
      options: ['None', '3.5mm Combo', 'Separate Input/Output', 'Multiple'],
      group: 'features',
    },
    {
      name: 'powerDelivery',
      type: 'radio',
      label: 'Power Delivery to Surface',
      required: true,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'originalMicrosoft',
      type: 'radio',
      label: 'Original Microsoft Product',
      required: false,
      options: ['Yes', 'No'],
      group: 'additional',
    },
    {
      name: 'securityFeatures',
      type: 'checkbox-group',
      label: 'Security Features',
      required: false,
      options: ['None', 'Kensington Lock Slot', 'Desk Mount Option', 'Multiple'],
      group: 'features',
    },
    {
      name: 'powerAdapter',
      type: 'radio',
      label: 'Power Adapter Included',
      required: false,
      options: ['Yes', 'No'],
      group: 'package',
    },
    {
      name: 'color',
      type: 'select',
      label: 'Color',
      required: false,
      options: ['Black', 'Gray', 'Silver', 'Platinum', 'Other'],
      group: 'physical',
    },
    {
      name: 'warranty',
      type: 'select',
      label: 'Warranty',
      required: false,
      options: ['1 Year', '2 Years', '3 Years', '5 Years', 'Lifetime'],
      group: 'additional',
    }
  ],
};
