import {CategoryFormConfig} from './product-form.types';

export const thunderboltCablesConfig: CategoryFormConfig = {
  id: 'thunderbolt_cables',
  name: 'Thunderbolt Cables',
  fields: [
    {
      name: 'version',
      type: 'select',
      label: 'Thunderbolt Version',
      required: true,
      options: ['Thunderbolt 2', 'Thunderbolt 3', 'Thunderbolt 4'],
      group: 'specifications',
    },
    {
      name: 'length',
      type: 'number',
      label: 'Cable Length',
      required: true,
      unit: 'm',
      group: 'specifications',
    },
    {
      name: 'maxSpeed',
      type: 'select',
      label: 'Maximum Speed',
      required: true,
      options: ['10Gbps', '20Gbps', '40Gbps'],
      group: 'specifications',
    },
    {
      name: 'powerDelivery',
      type: 'radio',
      label: 'Power Delivery Support',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'maxPowerWattage',
      type: 'select',
      label: 'Maximum PD Wattage',
      required: false,
      options: ['None', '60W', '100W', '240W'],
      group: 'features',
    },
    {
      name: 'cableType',
      type: 'select',
      label: 'Cable Type',
      required: false,
      options: ['Active', 'Passive'],
      group: 'specifications',
    },
    {
      name: 'intelCertified',
      type: 'radio',
      label: 'Intel Certified',
      required: false,
      options: ['Yes', 'No'],
      group: 'certification',
    },
    {
      name: 'displaySupport',
      type: 'select',
      label: 'Display Support',
      required: false,
      options: ['Single 4K', 'Dual 4K', 'Single 5K', 'Single 6K', 'Multiple Displays'],
      group: 'features',
    },
    {
      name: 'connectorType',
      type: 'select',
      label: 'Connector Type',
      required: true,
      options: ['Mini DisplayPort to Mini DisplayPort', 'USB-C to USB-C', 'USB-C to Mini DisplayPort'],
      group: 'specifications',
    },
    {
      name: 'color',
      type: 'select',
      label: 'Color',
      required: false,
      options: ['Black', 'White', 'Gray', 'Silver'],
      group: 'physical',
    },
    {
      name: 'warranty',
      type: 'select',
      label: 'Warranty',
      required: false,
      options: ['1 Year', '2 Years', '5 Years', 'Lifetime'],
      group: 'additional',
    }
  ],
};
