import {CategoryFormConfig} from './product-form.types';

export const trsCablesConfig: CategoryFormConfig = {
  id: 'trs_cables',
  name: 'TRS (Tip-Ring-Sleeve) Cables',
  fields: [
    {
      name: 'length',
      type: 'number',
      label: 'Cable Length',
      required: true,
      unit: 'm',
      group: 'specifications',
    },
    {
      name: 'connectorSize',
      type: 'select',
      label: 'Connector Size',
      required: true,
      options: ['1/4" (6.35mm)', '1/8" (3.5mm)', 'Mini (2.5mm)'],
      group: 'specifications',
    },
    {
      name: 'connectorType',
      type: 'select',
      label: 'Connector Configuration',
      required: true,
      options: [
        'TRS to TRS (Same Size)',
        'TRS to TRS (Different Sizes)',
        'TRS to XLR Male',
        'TRS to XLR Female',
        'TRS to RCA',
        'TRS to TS'
      ],
      group: 'specifications',
    },
    {
      name: 'signalType',
      type: 'select',
      label: 'Signal Type',
      required: true,
      options: ['Balanced Mono', 'Unbalanced Stereo', 'Insert Cable (Y-Split)'],
      group: 'specifications',
    },
    {
      name: 'goldPlated',
      type: 'radio',
      label: 'Gold-Plated Connectors',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'connectorStyle',
      type: 'select',
      label: 'Connector Style',
      required: false,
      options: ['Straight', 'Right Angle', 'L-Shaped', 'Mixed (One Straight, One Angled)'],
      group: 'specifications',
    },
    {
      name: 'conductorMaterial',
      type: 'select',
      label: 'Conductor Material',
      required: false,
      options: ['Copper', 'Oxygen-Free Copper (OFC)', 'Silver-Plated Copper', 'Premium Alloy'],
      group: 'specifications',
    },
    {
      name: 'shielding',
      type: 'select',
      label: 'Shielding Type',
      required: false,
      options: ['Standard', 'Double', 'Triple', 'Braided', 'Premium Noise Rejection'],
      group: 'specifications',
    },
    {
      name: 'application',
      type: 'select',
      label: 'Primary Application',
      required: false,
      options: ['Studio Recording', 'Live Sound', 'Headphones', 'Instruments', 'DJ Equipment', 'General Purpose'],
      group: 'compatibility',
    },
    {
      name: 'cableMaterial',
      type: 'select',
      label: 'Cable Jacket Material',
      required: false,
      options: ['PVC', 'Braided Nylon', 'Tweed', 'Rubber', 'Neutrik Connectors'],
      group: 'physical',
    },
    {
      name: 'color',
      type: 'select',
      label: 'Color',
      required: false,
      options: ['Black', 'Red', 'Blue', 'Green', 'Yellow', 'White', 'Multi-Color'],
      group: 'physical',
    },
    {
      name: 'lowCapacitance',
      type: 'radio',
      label: 'Low Capacitance Design',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'warranty',
      type: 'select',
      label: 'Warranty',
      required: false,
      options: ['1 Year', '2 Years', '5 Years', 'Lifetime'],
      group: 'additional',
    }
  ],
};
