import {CategoryFormConfig} from './product-form.types';

export const tsCablesConfig: CategoryFormConfig = {
  id: 'ts_cables',
  name: 'TS (Tip-Sleeve) Instrument Cables',
  fields: [
    {
      name: 'length',
      type: 'number',
      label: 'Cable Length',
      required: true,
      unit: 'm',
      group: 'specifications',
    },
    {
      name: 'connectorSize',
      type: 'select',
      label: 'Connector Size',
      required: true,
      options: ['1/4" (6.35mm)', '1/8" (3.5mm)'],
      group: 'specifications',
    },
    {
      name: 'connectorType',
      type: 'select',
      label: 'Connector Configuration',
      required: true,
      options: [
        'TS to TS (Same Size)',
        'TS to TS (Different Sizes)',
        'TS to RCA',
        'TS to XLR',
        'TS to TRS'
      ],
      group: 'specifications',
    },
    {
      name: 'instrumentType',
      type: 'select',
      label: 'Primary Instrument Type',
      required: false,
      options: ['Electric Guitar', 'Bass Guitar', 'Keyboard/Synth', 'General Instrument', 'Pedal/Effects Connection'],
      group: 'compatibility',
    },
    {
      name: 'goldPlated',
      type: 'radio',
      label: 'Gold-Plated Connectors',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'connectorStyle',
      type: 'select',
      label: 'Connector Style',
      required: false,
      options: ['Straight', 'Right Angle', 'L-Shaped', 'Mixed (One Straight, One Angled)'],
      group: 'specifications',
    },
    {
      name: 'cableGauge',
      type: 'select',
      label: 'Cable Gauge',
      required: false,
      options: ['24 AWG', '22 AWG', '20 AWG', '18 AWG'],
      group: 'specifications',
    },
    {
      name: 'shielding',
      type: 'select',
      label: 'Shielding Type',
      required: false,
      options: ['Standard', 'Double', 'Triple', 'Braided', 'Noise-Free'],
      group: 'specifications',
    },
    {
      name: 'conductorMaterial',
      type: 'select',
      label: 'Conductor Material',
      required: false,
      options: ['Copper', 'Oxygen-Free Copper (OFC)', 'Silver-Plated Copper', 'Premium Alloy'],
      group: 'specifications',
    },
    {
      name: 'cableMaterial',
      type: 'select',
      label: 'Cable Jacket Material',
      required: false,
      options: ['PVC', 'Braided Nylon', 'Tweed', 'Rubber', 'Neutrik Connectors', 'Silent Plug'],
      group: 'physical',
    },
    {
      name: 'noiseReduction',
      type: 'radio',
      label: 'Noise Reduction Technology',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'lowCapacitance',
      type: 'radio',
      label: 'Low Capacitance Design',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'color',
      type: 'select',
      label: 'Color',
      required: false,
      options: ['Black', 'Red', 'Blue', 'Green', 'Yellow', 'White', 'Tweed Pattern'],
      group: 'physical',
    },
    {
      name: 'warranty',
      type: 'select',
      label: 'Warranty',
      required: false,
      options: ['1 Year', '2 Years', '5 Years', 'Lifetime'],
      group: 'additional',
    }
  ],
};
