import {CategoryFormConfig} from './product-form.types';

export const usbCToUsbAConfig: CategoryFormConfig = {
  id: 'usb_c_to_usb_a',
  name: 'USB-C to USB-A',
  fields: [
    {
      name: 'direction',
      type: 'select',
      label: 'Connection Direction',
      required: true,
      options: ['USB-C Male to USB-A Female', 'USB-C Female to USB-A Male'],
      group: 'specifications',
    },
    {
      name: 'length',
      type: 'number',
      label: 'Cable Length (if applicable)',
      required: false,
      unit: 'cm',
      group: 'specifications',
    },
    {
      name: 'adapterType',
      type: 'select',
      label: 'Adapter Type',
      required: false,
      options: ['Cable', 'Dongle/Adapter'],
      group: 'physical',
    },
    {
      name: 'usbVersion',
      type: 'select',
      label: 'USB Version',
      required: true,
      options: ['USB 2.0', 'USB 3.0', 'USB 3.1 Gen 1', 'USB 3.1 Gen 2', 'USB 3.2'],
      group: 'specifications',
    },
    {
      name: 'dataTransferRate',
      type: 'select',
      label: 'Data Transfer Rate',
      required: false,
      options: ['Up to 480 Mbps', 'Up to 5 Gbps', 'Up to 10 Gbps', 'Up to 20 Gbps'],
      group: 'specifications',
    },
    {
      name: 'chargingSupport',
      type: 'radio',
      label: 'Charging Support',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'maxCurrent',
      type: 'select',
      label: 'Maximum Current',
      required: false,
      options: ['0.5A', '1A', '2A', '3A', '5A'],
      group: 'specifications',
    },
    {
      name: 'powerDelivery',
      type: 'radio',
      label: 'USB-C Power Delivery Support',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'cableMaterial',
      type: 'select',
      label: 'Cable Material',
      required: false,
      options: ['Standard PVC', 'Braided Nylon', 'TPE', 'Premium Materials'],
      group: 'physical',
    },
    {
      name: 'connectorFinish',
      type: 'select',
      label: 'Connector Finish',
      required: false,
      options: ['Standard', 'Gold-Plated', 'Nickel-Plated'],
      group: 'specifications',
    },
    {
      name: 'compatibleDevices',
      type: 'select',
      label: 'Primary Compatible Devices',
      required: false,
      options: ['USB-C Laptops', 'USB-C Smartphones', 'USB-C Tablets', 'All USB-C Devices'],
      group: 'compatibility',
    },
    {
      name: 'color',
      type: 'select',
      label: 'Color',
      required: false,
      options: ['Black', 'White', 'Silver', 'Space Gray', 'Rose Gold'],
      group: 'physical',
    },
    {
      name: 'warranty',
      type: 'select',
      label: 'Warranty',
      required: false,
      options: ['1 Year', '2 Years', '3 Years', '5 Years', 'Lifetime'],
      group: 'additional',
    }
  ],
};
