import {CategoryFormConfig} from './product-form.types';

export const usbCTo35mmConfig: CategoryFormConfig = {
  id: 'lightning_to_3_5mm_adapter',
  name: 'USB-C to 3.5mm Adapter',
  fields: [
    {
      name: 'length',
      type: 'number',
      label: 'Cable Length',
      required: true,
      unit: 'cm',
      group: 'specifications',
    },
    {
      name: 'audioQuality',
      type: 'select',
      label: 'Audio Quality',
      required: false,
      options: ['Standard', 'HD Audio', 'Hi-Res Audio'],
      group: 'specifications',
    },
    {
      name: 'dacType',
      type: 'select',
      label: 'DAC Type',
      required: false,
      options: ['Standard', '24-bit', '32-bit', 'Hi-Fi', 'Not Specified'],
      group: 'specifications',
    },
    {
      name: 'sampleRate',
      type: 'select',
      label: 'Maximum Sample Rate',
      required: false,
      options: ['44.1kHz', '48kHz', '96kHz', '192kHz', 'Not Specified'],
      group: 'specifications',
    },
    {
      name: 'impedanceSupport',
      type: 'select',
      label: 'Headphone Impedance Support',
      required: false,
      options: ['Standard (Up to 32Ω)', 'Medium (Up to 100Ω)', 'High (100Ω+)'],
      group: 'specifications',
    },
    {
      name: 'remoteControl',
      type: 'radio',
      label: 'Remote Control Support',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'micSupport',
      type: 'radio',
      label: 'Microphone Support',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'powerDeliveryPassthrough',
      type: 'radio',
      label: 'Power Delivery Passthrough',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'compatibleDevices',
      type: 'select',
      label: 'Primary Compatible Devices',
      required: false,
      options: ['Android Phones', 'iPad Pro', 'MacBooks', 'Windows Laptops', 'All USB-C Devices'],
      group: 'compatibility',
    },
    {
      name: 'connectorMaterial',
      type: 'select',
      label: 'Connector Material',
      required: false,
      options: ['Plastic', 'Metal', 'Aluminum Alloy'],
      group: 'physical',
    },
    {
      name: 'color',
      type: 'select',
      label: 'Color',
      required: false,
      options: ['Black', 'White', 'Silver', 'Space Gray'],
      group: 'physical',
    },
    {
      name: 'warranty',
      type: 'select',
      label: 'Warranty',
      required: false,
      options: ['1 Year', '2 Years', '3 Years', '5 Years', 'Lifetime'],
      group: 'additional',
    }
  ],
};
