import {CategoryFormConfig} from './product-form.types';

export const usbToEthernetAdaptersConfig: CategoryFormConfig = {
  id: 'usb_to_ethernet_adapters',
  name: 'USB to Ethernet Adapters',
  fields: [
    {
      name: 'usbVersion',
      type: 'select',
      label: 'USB Version',
      required: true,
      options: ['USB 2.0', 'USB 3.0', 'USB 3.1', 'USB 3.2', 'USB-C'],
      group: 'specifications',
    },
    {
      name: 'ethernetSpeed',
      type: 'select',
      label: 'Ethernet Speed',
      required: true,
      options: ['10/100 Mbps', '10/100/1000 Mbps (Gigabit)', '2.5 Gbps', '5 Gbps', '10 Gbps'],
      group: 'specifications',
    },
    {
      name: 'chipset',
      type: 'select',
      label: 'Chipset',
      required: false,
      options: ['Realtek', 'ASIX', 'Intel', 'Broadcom', 'Other'],
      group: 'specifications',
    },
    {
      name: 'powerDeliveryPassthrough',
      type: 'radio',
      label: 'Power Delivery Passthrough',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'additionalPorts',
      type: 'select',
      label: 'Additional Ports',
      required: false,
      options: ['None', 'USB Hub', 'Card Reader', 'HDMI', 'Multiple'],
      group: 'features',
    },
    {
      name: 'compatibleOs',
      type: 'select',
      label: 'Compatible Operating Systems',
      required: true,
      options: ['Windows', 'macOS', 'Linux', 'Chrome OS', 'Windows/macOS', 'All Major OS'],
      group: 'compatibility',
    },
    {
      name: 'driverRequired',
      type: 'radio',
      label: 'Driver Required',
      required: false,
      options: ['Yes', 'No'],
      group: 'compatibility',
    },
    {
      name: 'cableLength',
      type: 'number',
      label: 'Cable Length (if applicable)',
      required: false,
      unit: 'cm',
      group: 'physical',
    },
    {
      name: 'compactDesign',
      type: 'radio',
      label: 'Compact Design',
      required: false,
      options: ['Yes', 'No'],
      group: 'physical',
    },
    {
      name: 'color',
      type: 'select',
      label: 'Color',
      required: false,
      options: ['Black', 'White', 'Silver', 'Gray', 'Blue'],
      group: 'physical',
    },
    {
      name: 'ledIndicator',
      type: 'radio',
      label: 'LED Indicator',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'warranty',
      type: 'select',
      label: 'Warranty',
      required: false,
      options: ['1 Year', '2 Years', '3 Years', '5 Years', 'Lifetime'],
      group: 'additional',
    }
  ],
};
