import {CategoryFormConfig} from './product-form.types';

export const usbAHubsConfig: CategoryFormConfig = {
  id: 'usb_a_hubs',
  name: 'USB-A Hubs',
  fields: [
    {
      name: 'totalPorts',
      type: 'number',
      label: 'Total Number of Ports',
      required: true,
      group: 'specifications',
    },
    {
      name: 'usbVersion',
      type: 'select',
      label: 'USB Version',
      required: true,
      options: ['USB 1.1', 'USB 2.0', 'USB 3.0', 'USB 3.1', 'USB 3.2'],
      group: 'specifications',
    },
    {
      name: 'dataTransferSpeed',
      type: 'select',
      label: 'Data Transfer Speed',
      required: false,
      options: ['Up to 12 Mbps', 'Up to 480 Mbps', 'Up to 5 Gbps', 'Up to 10 Gbps'],
      group: 'specifications',
    },
    {
      name: 'portArrangement',
      type: 'select',
      label: 'Port Arrangement',
      required: false,
      options: ['In-line', 'Clustered', 'Circular', 'Stacked'],
      group: 'physical',
    },
    {
      name: 'powerSupply',
      type: 'select',
      label: 'Power Supply',
      required: false,
      options: ['Bus-Powered', 'Self-Powered', 'Both Options'],
      group: 'specifications',
    },
    {
      name: 'ledIndicators',
      type: 'radio',
      label: 'LED Indicators',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'individualSwitches',
      type: 'radio',
      label: 'Individual Port Switches',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'cableLength',
      type: 'number',
      label: 'Cable Length',
      required: false,
      unit: 'cm',
      group: 'physical',
    },
    {
      name: 'cableFixed',
      type: 'radio',
      label: 'Fixed Cable',
      required: false,
      options: ['Yes', 'No'],
      group: 'physical',
    },
    {
      name: 'compatibleSystems',
      type: 'checkbox-group',
      label: 'Compatible Operating Systems',
      required: false,
      options: ['Windows', 'macOS', 'Linux', 'Chrome OS', 'All Major OS'],
      group: 'compatibility',
    },
    {
      name: 'mountingOptions',
      type: 'checkbox-group',
      label: 'Mounting Options',
      required: false,
      options: ['None', 'Adhesive', 'Screw Mount', 'Clip', 'Multiple'],
      group: 'physical',
    },
    {
      name: 'color',
      type: 'select',
      label: 'Color',
      required: false,
      options: ['Black', 'White', 'Silver', 'Blue', 'Other'],
      group: 'physical',
    },
    {
      name: 'warranty',
      type: 'select',
      label: 'Warranty',
      required: false,
      options: ['1 Year', '2 Years', '3 Years', '5 Years', 'Lifetime'],
      group: 'additional',
    }
  ],
};
