import {CategoryFormConfig} from './product-form.types';

export const usbcToHdmiAdaptersConfig: CategoryFormConfig = {
  id: 'usb_c_to_hdmi_adapters',
  name: 'USB-C to HDMI Adapters',
  fields: [
    {
      name: 'hdmiVersion',
      type: 'select',
      label: 'HDMI Version',
      required: true,
      options: ['HDMI 1.4', 'HDMI 2.0', 'HDMI 2.1'],
      group: 'specifications',
    },
    {
      name: 'maxResolution',
      type: 'select',
      label: 'Maximum Resolution',
      required: true,
      options: ['1080p (1920×1080)', '1440p (2560×1440)', '4K (3840×2160)', '5K (5120×2880)', '8K (7680×4320)'],
      group: 'specifications',
    },
    {
      name: 'refreshRate',
      type: 'select',
      label: 'Maximum Refresh Rate at Highest Resolution',
      required: true,
      options: ['30Hz', '60Hz', '120Hz', '144Hz', '240Hz'],
      group: 'specifications',
    },
    {
      name: 'altModeSupport',
      type: 'radio',
      label: 'USB-C Alt Mode Support',
      required: true,
      options: ['Yes', 'No'],
      group: 'specifications',
    },
    {
      name: 'thunderboltCompatible',
      type: 'radio',
      label: 'Thunderbolt Compatible',
      required: false,
      options: ['Yes', 'No'],
      group: 'compatibility',
    },
    {
      name: 'powerDeliveryPassthrough',
      type: 'radio',
      label: 'Power Delivery Passthrough',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'pdWattage',
      type: 'select',
      label: 'Power Delivery Wattage (if applicable)',
      required: false,
      options: ['Not Applicable', 'Up to 60W', 'Up to 87W', 'Up to 100W'],
      group: 'features',
    },
    {
      name: 'additionalPorts',
      type: 'select',
      label: 'Additional Ports',
      required: false,
      options: ['None', 'USB-A', 'USB-C', 'Ethernet', 'Audio', 'Multiple'],
      group: 'features',
    },
    {
      name: 'hdrSupport',
      type: 'radio',
      label: 'HDR Support',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'hdcpSupport',
      type: 'select',
      label: 'HDCP Support',
      required: false,
      options: ['HDCP 1.4', 'HDCP 2.2', 'HDCP 2.3', 'None'],
      group: 'specifications',
    },
    {
      name: 'compatibleDevices',
      type: 'select',
      label: 'Compatible Devices',
      required: false,
      options: ['MacBook/MacBook Pro', 'Windows Laptops', 'iPad Pro', 'Android Devices', 'All USB-C Devices with DP Alt Mode'],
      group: 'compatibility',
    },
    {
      name: 'cableLength',
      type: 'number',
      label: 'Cable Length (if applicable)',
      required: false,
      unit: 'cm',
      group: 'physical',
    },
    {
      name: 'color',
      type: 'select',
      label: 'Color',
      required: false,
      options: ['Black', 'White', 'Silver', 'Space Gray', 'Gold'],
      group: 'physical',
    },
    {
      name: 'warranty',
      type: 'select',
      label: 'Warranty',
      required: false,
      options: ['1 Year', '2 Years', '3 Years', '5 Years', 'Lifetime'],
      group: 'additional',
    }
  ],
};
