import {CategoryFormConfig} from './product-form.types';

export const usbcHubsConfig: CategoryFormConfig = {
  id: 'usb_c_hubs',
  name: 'USB-C Hubs',
  fields: [
    {
      name: 'totalPorts',
      type: 'number',
      label: 'Total Number of Ports',
      required: true,
      group: 'specifications',
    },
    {
      name: 'usbCPorts',
      type: 'number',
      label: 'USB-C Ports',
      required: true,
      group: 'specifications',
    },
    {
      name: 'usbAPorts',
      type: 'number',
      label: 'USB-A Ports',
      required: true,
      group: 'specifications',
    },
    {
      name: 'usbVersion',
      type: 'select',
      label: 'USB Version',
      required: false,
      options: ['USB 2.0', 'USB 3.0', 'USB 3.1', 'USB 3.2 Gen 1', 'USB 3.2 Gen 2', 'USB 4.0'],
      group: 'specifications',
    },
    {
      name: 'displayPorts',
      type: 'checkbox-group',
      label: 'Display Port Types',
      required: false,
      options: ['None', 'HDMI', 'DisplayPort', 'VGA', 'Multiple Types'],
      group: 'specifications',
    },
    {
      name: 'ethernetPort',
      type: 'radio',
      label: 'Ethernet Port',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'cardReader',
      type: 'radio',
      label: 'Memory Card Reader',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'audioJack',
      type: 'radio',
      label: 'Audio Jack',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'powerDelivery',
      type: 'radio',
      label: 'Power Delivery Passthrough',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'maxPowerDelivery',
      type: 'select',
      label: 'Maximum Power Delivery',
      required: false,
      options: ['Not Applicable', '30W', '45W', '60W', '87W', '100W'],
      group: 'specifications',
    },
    {
      name: 'portArrangement',
      type: 'select',
      label: 'Port Arrangement',
      required: false,
      options: ['In-line', 'Clustered', 'Both Sides', 'Circular'],
      group: 'physical',
    },
    {
      name: 'cableLength',
      type: 'number',
      label: 'Cable Length',
      required: false,
      unit: 'cm',
      group: 'physical',
    },
    {
      name: 'cableFixed',
      type: 'radio',
      label: 'Fixed Cable',
      required: false,
      options: ['Yes', 'No'],
      group: 'physical',
    },
    {
      name: 'compactDesign',
      type: 'radio',
      label: 'Compact Design',
      required: false,
      options: ['Yes', 'No'],
      group: 'physical',
    },
    {
      name: 'color',
      type: 'select',
      label: 'Color',
      required: false,
      options: ['Black', 'Silver', 'White', 'Gray', 'Other'],
      group: 'physical',
    },
    {
      name: 'warranty',
      type: 'select',
      label: 'Warranty',
      required: false,
      options: ['1 Year', '2 Years', '3 Years', '5 Years', 'Lifetime'],
      group: 'additional',
    }
  ],
};
