import {CategoryFormConfig} from './product-form.types';

export const usbcDockingStationsConfig: CategoryFormConfig = {
  id: 'usb_c_docking_stations',
  name: 'USB-C Docking Stations',
  fields: [
    {
      name: 'totalPorts',
      type: 'number',
      label: 'Total Number of Ports',
      required: true,
      group: 'specifications',
    },
    {
      name: 'usbCPorts',
      type: 'number',
      label: 'USB-C Ports',
      required: true,
      group: 'specifications',
    },
    {
      name: 'usbAPorts',
      type: 'number',
      label: 'USB-A Ports',
      required: true,
      group: 'specifications',
    },
    {
      name: 'displayPorts',
      type: 'checkbox-group',
      label: 'Display Port Types',
      required: false,
      options: ['HDMI', 'DisplayPort', 'Mini DisplayPort', 'VGA', 'DVI', 'Thunderbolt', 'Multiple Types'],
      group: 'specifications',
    },
    {
      name: 'maxDisplays',
      type: 'select',
      label: 'Maximum External Displays',
      required: false,
      options: ['1', '2', '3', '4+'],
      group: 'specifications',
    },
    {
      name: 'maxResolution',
      type: 'select',
      label: 'Maximum Display Resolution',
      required: false,
      options: ['1080p (1920×1080)', '1440p (2560×1440)', '4K (3840×2160)', '5K (5120×2880)', '8K (7680×4320)'],
      group: 'specifications',
    },
    {
      name: 'ethernetPort',
      type: 'radio',
      label: 'Ethernet Port',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'ethernetSpeed',
      type: 'select',
      label: 'Ethernet Speed',
      required: false,
      options: ['10/100 Mbps', '10/100/1000 Mbps (Gigabit)', '2.5 Gbps', '5 Gbps', '10 Gbps'],
      group: 'specifications',
    },
    {
      name: 'cardReader',
      type: 'radio',
      label: 'Memory Card Reader',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'supportedCardFormats',
      type: 'checkbox-group',
      label: 'Supported Card Formats',
      required: false,
      options: ['SD', 'SDHC', 'SDXC', 'microSD', 'microSDHC', 'microSDXC', 'CF', 'Multiple Formats'],
      group: 'specifications',
    },
    {
      name: 'audioJacks',
      type: 'select',
      label: 'Audio Jacks',
      required: false,
      options: ['None', '3.5mm Combo', 'Separate Input/Output', 'Multiple'],
      group: 'features',
    },
    {
      name: 'powerDelivery',
      type: 'radio',
      label: 'Power Delivery Support',
      required: true,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'maxPowerDelivery',
      type: 'select',
      label: 'Maximum Power Delivery',
      required: false,
      options: ['Not Applicable', '30W', '45W', '60W', '85W', '87W', '96W', '100W', '140W+'],
      group: 'specifications',
    },
    {
      name: 'dataTransferSpeed',
      type: 'select',
      label: 'Data Transfer Speed',
      required: false,
      options: ['Up to 5 Gbps', 'Up to 10 Gbps', 'Up to 20 Gbps', 'Up to 40 Gbps'],
      group: 'specifications',
    },
    {
      name: 'compatibleSystems',
      type: 'checkbox-group',
      label: 'Compatible Operating Systems',
      required: false,
      options: ['Windows', 'macOS', 'Chrome OS', 'Linux', 'Multiple OS'],
      group: 'compatibility',
    },
    {
      name: 'additionalFeatures',
      type: 'checkbox-group',
      label: 'Additional Features',
      required: false,
      options: ['Detachable Cable', 'LED Indicators', 'Security Lock Slot', 'Button Controls', 'Multiple'],
      group: 'features',
    },
    {
      name: 'powerSource',
      type: 'select',
      label: 'Power Source',
      required: false,
      options: ['Bus-Powered', 'AC Adapter', 'Both'],
      group: 'specifications',
    },
    {
      name: 'mountingOptions',
      type: 'select',
      label: 'Mounting Options',
      required: false,
      options: ['None', 'VESA Mount', 'Desk Clamp', 'Wall Mount', 'Multiple'],
      group: 'physical',
    },
    {
      name: 'color',
      type: 'select',
      label: 'Color',
      required: false,
      options: ['Black', 'Silver', 'Space Gray', 'White', 'Other'],
      group: 'physical',
    },
    {
      name: 'warranty',
      type: 'select',
      label: 'Warranty',
      required: false,
      options: ['1 Year', '2 Years', '3 Years', '5 Years', 'Lifetime'],
      group: 'additional',
    }
  ],
};
