import {CategoryFormConfig} from './product-form.types';

export const xlrCablesConfig: CategoryFormConfig = {
  id: 'xlr_cables',
  name: 'XLR Cables',
  fields: [
    {
      name: 'length',
      type: 'number',
      label: 'Cable Length',
      required: true,
      unit: 'm',
      group: 'specifications',
    },
    {
      name: 'connectorType',
      type: 'select',
      label: 'Connector Type',
      required: true,
      options: ['XLR Male to XLR Female', 'XLR Male to 3.5mm', 'XLR to TRS', 'XLR to RCA'],
      group: 'specifications',
    },
    {
      name: 'cableGauge',
      type: 'select',
      label: 'Cable Gauge',
      required: false,
      options: ['24 AWG', '22 AWG', '20 AWG', '18 AWG'],
      group: 'specifications',
    },
    {
      name: 'balancedAudio',
      type: 'radio',
      label: 'Balanced Audio',
      required: false,
      options: ['Yes', 'No'],
      group: 'specifications',
    },
    {
      name: 'goldPlated',
      type: 'radio',
      label: 'Gold-Plated Connectors',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'xlrPinCount',
      type: 'select',
      label: 'XLR Pin Count',
      required: false,
      options: ['3-pin', '4-pin', '5-pin', '7-pin'],
      group: 'specifications',
    },
    {
      name: 'oxygenFreeCable',
      type: 'radio',
      label: 'Oxygen-Free Copper',
      required: false,
      options: ['Yes', 'No'],
      group: 'features',
    },
    {
      name: 'shielding',
      type: 'select',
      label: 'Shielding Quality',
      required: false,
      options: ['Standard', 'Double', 'Triple', 'Premium'],
      group: 'specifications',
    },
    {
      name: 'cableMaterial',
      type: 'select',
      label: 'Cable Material',
      required: false,
      options: ['Standard PVC', 'Braided', 'Neutrik Connectors', 'Professional Grade'],
      group: 'physical',
    },
    {
      name: 'color',
      type: 'select',
      label: 'Color',
      required: false,
      options: ['Black', 'Blue', 'Red', 'Yellow', 'White'],
      group: 'physical',
    },
    {
      name: 'warranty',
      type: 'select',
      label: 'Warranty',
      required: false,
      options: ['1 Year', '2 Years', '5 Years', 'Lifetime'],
      group: 'additional',
    }
  ],
};
